[package]
name = "strava-gpx"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]

[dependencies]
xmltree = "0.6"
error-chain = "0.11"
rayon = "0.8"
chrono = "0.4"
geo = "0.6"
itertools = "0.6"

[dev-dependencies]
glob = "0.2"
reqwest = "0.8"
dotenv = "0.10"
